### ISSUE TITLE
Page break does not work in production

### ISSUE THREAD

**Issue by ItaiYuda** [christopherdro/react-native-html-to-pdf#263]
Hi,

I am trying to set a page break in a pdf A4 page.

My options:

```js
let options = {
    html,
    width: 595,
    height: 842,
    fileName: ...myFileName,
    directory: 'Documents'
};
```

I added a class with page break properties to the html style and added the class before the Weather section div:

```css
.page-break-before {
    display: block;
    page-break-before: always; 
    page-break-after: auto;
    page-break-inside: avoid;
}
```

when I generate the pdf, in the dev environment everything works as expected:

*(The page break should appear before the Weather section)*

![image](https://user-images.githubusercontent.com/26575456/155332070-aae81b40-d17b-409a-8fdf-f14781064c53.png)

but in production, the page break doesn't seem to work:

![image](https://user-images.githubusercontent.com/26575456/155332264-dd2e9450-0892-4f19-858b-f23416d941c3.png)

## OS
It occurs on Android only.

## Environment

```json
"react-native-html-to-pdf": "0.11.0",
"react": "17.0.2",
"react-native": "0.64.2",
```
