### ISSUE TITLE
Great Library! Anyway to use custom Fonts in iOS?

### ISSUE THREAD

**Issue by eroy4u** [christopherdro/react-native-html-to-pdf#49]
I really need to use custom fonts in iOS,
anyway or anywhere should I look to modify the code. I could issue a pull request once done.

**Comment by EEimer** [comment]
I used this lib, but really needed to add my own font..
It actually is quit easy:
1) add font to iOS
2) get name 
3) set html

https://stackoverflow.com/a/12697144/1996216

**Comment by christopherdro** [comment]
Nice! Yea that should work. The process of adding fonts is the same as any other react native project.

Make sure you've entered the font family correctly. To double check your font has been loaded correctly you could pop the following in Appdelegate somewhere to test.

```obj-c
for (NSString *familyName in [UIFont familyNames]){
    NSLog(@"Family name: %@", familyName);
    for (NSString *fontName in [UIFont fontNamesForFamilyName:familyName]) {
        NSLog(@"--Font name: %@", fontName);
    }
}
```

Would be great if someone could PR an update to the docs explaining this.

**Comment by 1awaleed** [comment]
Hello @christopherdro @EEimer 
Can you please expand more on how did you use the font in your css on iOS or give a specific example?
I followed the steps below **but it did not work unfortunately** 

1- Added the font file `SF-Pro-Display-Regular.otf` to my assets.
2- Run `react-native link` -> Font gets added to `info.plist` & to my project `./resources`
3- I ran @christopherdro 's couple of lines & got
   ```
2020-08-18 13:17:31.973644+0200 xxxx[31816:1351894] Family name: SF Pro Display
2020-08-18 13:17:31.973709+0200 xxxx[31816:1351894] --Font name: SFProDisplay-Regular
```
4- Then I applied the style tag just like @EEimer suggested
```css
<style type="text/css">
    @font-face {
        font-family: 'SF Pro Display';
        src: url('SF-Pro-Display-Regular.otf') format('truetype')
    }
    body {
        $ {this._font} $ {this._fontSizeNormal}
    }
</style>
```
